### PR TITLE
Added perl and vim

### PR DESCRIPTION
**Pull request by ryanrdetzel**
Hopefully others want vim too!

### CODE REVIEW

**Comment by eschultz** [comment]
Thanks Ryan!  I'll have to flip the author back to eschultz so the repo url works, but I'll give you credit in the change log like I did for David Coppit if that's cool with you?

You guys using unRAID at Twitter yet? :smile:

**Comment by JustinAiken** [comment]
:+1: Yaaay no more `nano`ing on my box! :+1:

**Comment by ryanrdetzel** [comment]
I don't even need credit, I just really need vim. :-) The sooner you can merge the better so I can go back to using the official nerdpack!

Unraid is great but it can't handle Twitter scale. Not yet anyway.

**Comment by eschultz** [comment]
I bumped the new version and tagged it on my repo so it should be live now.  Thanks again.

We tested some write speeds recently using 12x HDDs in a btrfs pool and were able to fully saturate a 10Gbps network card for the duration of a 60TB transfer.  We don't have any FC or Infiniband networking equipment to test with but sky's the limit if we swap out the slow HDDs for SSDs or NVMe flash storage :+1:

**Pull request merged**
